apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-backend-deploy
  namespace: ai-agent-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-backend
  template:
    metadata:
      labels:
        app: test-backend
    spec:
      containers:
        - name: backend
          image: asif1993/test-backend:v1
          ports:
            - containerPort: 8000
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: all-secrets-here
                  key: GROQ_API_KEY
